// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjpsjeqxgtnfgyqunfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuanBzamVxeGd0bmZneXF1bmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MDEzMTYsImV4cCI6MjA4NTE3NzMxNn0.kPB5MBhfxVeBWQFrKOQy6b3FtVl9mx20481zxDn6-so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});